# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://jhipster.github.io/profiles/
# More information on configuration properties: https://jhipster.github.io/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        include: swagger,no-liquibase
#        include: no-liquibase
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        #url: jdbc:oracle:thin:@112.72.97.196:1521:ORCL
        #username: bikt_dw
        #password: Viettel#123
        #url: jdbc:oracle:thin:@10.29.83.159:1521:TRADEOLDEV
        url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=10.29.83.159)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=pdbagency)))
        username: agencyuat
        password: agencyuat
        hikari:
            minimum-idle: 5
            maximum-pool-size: 40
            idle-timeout: 30000
            max-lifetime: 2000000
            connection-timeout: 60000
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        database: ORACLE
        show-sql: true
        properties:
#           hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    cas:
        enabled: false
        ticket-url: https://cas.baoviet.org:8443/cas/v1/tickets
    mail:
        host: mail.baoviet.com.vn
        port: 25
        username: bvspp@baoviet.com.vn
        password: spp0987
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false
    upload:
        folder-upload: /root/agency/temp/

liquibase:
    contexts: prod

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias BaoViet-Agency -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        keyStoreType: PKCS12
#        keyAlias: BaoViet-Agency
# ===================================================================
server:
    port: ${PORT:9090}

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers: Authorization,Link,X-Application-Context,X-Content-Type-Options,X-Total-Count,X-Xss-Protection
        allow-credentials: true
        max-age: 1800
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: BaoViet-Agency@localhost
        base-url: http://127.0.0.1:8080
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: false
        graphite: # Use the "graphite" Maven profile to have the Graphite dependencies
            enabled: false
            host: localhost
            port: 2003
            prefix: BaoViet-Agency
        prometheus: # Use the "prometheus" Maven profile to have the Prometheus dependencies
            enabled: false
            endpoint: /prometheusMetrics
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            #host: 125.253.113.34
            host: 172.29.13.12
            port: 5000
            queue-size: 512

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://jhipster.github.io/common-application-properties/
# ===================================================================

payment:
    vi-viet:
        service-url: "https://sandbox.viviet.vn/vipay/ecommerce"
        return-url: "https://appuat.baoviet.com.vn:7778/api/agency/payment/returnViViet"
        merchant: "Bảo Việt Bảo Hiểm"
        merchant_site_id : "4314"
        access_code: "AH1982718872"
        sercurity_secret: "PG332642218196611948"
        version: "1.0"
        cid: "BVGI"
        did: "D04"
        client-ip: "10.36.20.47"
    l23-pay:
        service-url: "https://sandbox.123pay.vn/miservice/createOrder1"
        return-url: "https://appuat.baoviet.com.vn:7780/api/landing/123Pay"
        cancel-url: "https://appuat.baoviet.com.vn:7780/api/landing/123Pay"
        error-url: "https://appuat.baoviet.com.vn:7780/api/landing/123Pay"
        cid: "BVGI"
        did: "D04"
        client-ip: "10.36.20.47"
    momo:
        service-url: "https://test-payment.momo.vn/gw_payment/transactionProcessor"
        return-url-android: "https://appuat.baoviet.com.vn:7778/api/agency/payment/DeeplinkMoMo?device=1"
        return-url-ios: "https://appuat.baoviet.com.vn:7778/api/agency/payment/DeeplinkMoMo?device=0"
        return-url: "https://appuat.baoviet.com.vn:7778/api/agency/payment/returnMomo"
        notify-url: "https://appuat.baoviet.com.vn:7778/api/agency/payment/notifyMomo"
        partner-code: "123456"
        access-key: "F8BBA842ECF85"
        secret-key: "K951B6PE1waDMi640xX08PD3vg6EkVlz"
        cid: "BVGI"
        did: "D04"
    viettel-pay:
        service-url: "http://125.235.40.34:8085/ViettelSDKPayment/PaymentServlet"
        post-url: "http://125.235.40.34:8085/ViettelSDKPayment/webresources/postData"
        return-url: "https://appuat.baoviet.com.vn:7778/api/agency/payment/returnViettelPay"
        version: "1.0"
        command: "PAYMENT"
        merchant-code: "baoviet"
        access-code: "66b688e12af644ab883052df3a30a940"
        hash-key: "66b688e12af644ab883052df3a30a939"
        currency: "VND"
        cid: "BVGI"
        did: "D04"
    vn-pay:
#        service-url: "http://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
        service-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
        return-url: "https://appuat.baoviet.com.vn:7778/api/agency/payment/returnVnPay"
        querydr: "http://sandbox.vnpayment.vn/merchant_webapi/merchant.html"
        tmn-code: "BAOVIET1"
#        hash-secret: "ZDCASMNGXLNOJRLMGRQNSSUOXGEIGIDZ"
        hash-secret: "ZMWZWAEQCCOISAZRUPAGGNUFYEVOSIBC"
        version: "2.0.0"
        command: "pay"
        currency: "VND"
        cid: "BVGI"
        did: "D04"
application:
    http-proxy-address: 172.29.1.25
    http-proxy-port: 8080
#    payment-return-page: "https://appuat.baoviet.com.vn:7780/#/app/cart"
    payment-return-page: "https://appuat.baoviet.com.vn:7780/#/access/returnPayment"
    payment-mobile-return-page: "https://appuat.baoviet.com.vn:7780/#/payment-landing"