# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://jhipster.github.io/profiles/
# More information on configuration properties: https://jhipster.github.io/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    security:
        roles: ADMIN
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: BaoViet-Agency
        proxy:
            enable: true
            #address: 172.29.1.24
            #port: 8080
            #username: vuhoangchien
            #password: chien@123
            address: 172.29.1.25
            port: 8080
            username: thaihuychuong
            password: 12345678
        vendor:
            momo:
                secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
            adayroi:
                url: http://partner.8mall.vn
                grant_type: password
                client_id: consoleApp
                client_secret: adrpublicapi
                username: BVI_INS
                password: Adayroi@123456
        CID: AG
        DID: D05
        ws:
            printed-paper:
                baoviet:
                    #url: https://appuat.baoviet.com.vn:7779/BVAC02/BVAC_AGENCY.asmx
                    url: http://10.29.83.84/BVAC02/BVAC_AGENCY.asmx?wsdl
                    username: agency
                    password: 9A5459078CDFED5305E8F655F7586A36DFC1E46475ED937D53AFCDB468790C9E
            sms:
                url: http://172.29.1.76/INSUREJ_BRANDNAME/SMSSendService.asmx
                username: CMCT_BVHN
                password: cmctelecom
            eclaim:
                url: https://172.29.13.13:8080/api/manager/getClaimInformation
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true

info:
    project:
        version: #project.version#

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: BaoViet-Agency@localhost
    swagger:
        default-include-pattern: /api/agency/.*
        title: Baoviet Agency REST API
        description: REST API documentation for Baoviet Agency Project  <br> <a href="/content/extra_doc/common.html">Các bước thực hiện chung trước khi call API/Common steps before calling API</a> <br> <a href="/content/extra_doc/updateLog.html">Update log API</a>
        version: 0.0.1
        terms-of-service-url: https://baovietonline.com/
        contact-name: Nam, Nguyen Hoai
        contact-url:
        contact-email: namnh@itsol.vn
        license: Apache License Version 2.0
        license-url: https://www.apache.org/licenses/LICENSE-2.0
    ribbon:
        display-on-active-profiles: dev

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://jhipster.github.io/common-application-properties/
# ===================================================================

application: