
  CREATE TABLE "TRADEOL"."ADMIN_USER_PRODUCT_GROUP" 
   ("ADMIN_ID" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"GROUP_ID" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	 CHECK ("ADMIN_ID" IS NOT NULL) ENABLE, 
	 CHECK ("GROUP_ID" IS NOT NULL) ENABLE, 
	 PRIMARY KEY ("ADMIN_ID", "GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP"  ENABLE, 
	 CONSTRAINT "FK_ADMIN_ID" FOREIGN KEY ("ADMIN_ID")
	  REFERENCES "TRADEOL"."ADMIN_USER" ("ID") ENABLE, 
	 CONSTRAINT "FK_GROUP_ID" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "TRADEOL"."ADMIN_PRODUCT_GROUP" ("GROUP_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP" ;

COMMIT;