
  CREATE TABLE "TRADEOL"."ADMIN_ROLE_PERMISSION" 
   (	"ROLE_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"PERMISSION_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	 CHECK ("ROLE_NAME" IS NOT NULL) ENABLE, 
	 CHECK ("PERMISSION_NAME" IS NOT NULL) ENABLE, 
	 PRIMARY KEY ("ROLE_NAME", "PERMISSION_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP"  ENABLE, 
	 CONSTRAINT "FK_AD_ROLE" FOREIGN KEY ("ROLE_NAME")
	  REFERENCES "TRADEOL"."ADMIN_ROLE" ("NAME") ENABLE, 
	 CONSTRAINT "FK_AD_PERMISSION" FOREIGN KEY ("PERMISSION_NAME")
	  REFERENCES "TRADEOL"."ADMIN_PERMISSION" ("NAME") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP" ;
