
  CREATE TABLE "TRADEOL"."ADMIN_USER_USER_ROLE" 
   (	"ADMIN_ID" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"ROLE_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	 CHECK ("ADMIN_ID" IS NOT NULL) ENABLE, 
	 CHECK ("ROLE_NAME" IS NOT NULL) ENABLE, 
	 PRIMARY KEY ("ADMIN_ID", "ROLE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP"  ENABLE, 
	 CONSTRAINT "FK_ADMIN_USER_ADMIN_USER" FOREIGN KEY ("ADMIN_ID")
	  REFERENCES "TRADEOL"."ADMIN_USER" ("ID") ENABLE, 
	 CONSTRAINT "FK_ADMIN_ROLE" FOREIGN KEY ("ROLE_NAME")
	  REFERENCES "TRADEOL"."ADMIN_ROLE" ("NAME") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP" ;
