
  CREATE TABLE "TRADEOL"."AGENT_TMP_MOMO_CAR" 
   (	"ID" NVARCHAR2(60) NOT NULL ENABLE, 
	"REQUEST_ID" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"ACTUAL_VALUE" NUMBER(20,0), 
	"CHANGE_PREMIUM" NUMBER(20,0), 
	"CHASSIS_NUMBER" VARCHAR2(255 BYTE), 
	"ENGINE_NUMBER" VARCHAR2(255 BYTE), 
	"GARAGE_CHECK" NUMBER(1,0), 
	"INSURED_ADDRESS" VARCHAR2(255 BYTE), 
	"INSURED_NAME" VARCHAR2(255 BYTE), 
	"INVOICE_CHECK" NUMBER(1,0), 
	"INVOICE_NAME" VARCHAR2(255 BYTE), 
	"INVOICE_COMPANY" VARCHAR2(255 BYTE), 
	"INVOICE_TAX_NO" VARCHAR2(255 BYTE), 
	"INVOICE_ADDRESS" VARCHAR2(255 BYTE), 
	"INVOICE_ACCOUNT_NO" VARCHAR2(255 BYTE), 
	"KHAU_HAO_CHECK" NUMBER(1,0), 
	"KHAU_TRU_CHECK" NUMBER(1,0), 
	"MAKE_ID" VARCHAR2(255 BYTE), 
	"MAKE_NAME" VARCHAR2(255 BYTE), 
	"MAT_CAP_CHECK" NUMBER(1,0), 
	"MODEL_ID" VARCHAR2(255 BYTE), 
	"MODEL_NAME" VARCHAR2(255 BYTE), 
	"NNTX_CHECK" NUMBER(1,0), 
	"NGAP_NUOC_CHECK" NUMBER(1,0), 
	"PASSENGER_ACCIDENT_NUMBER" NUMBER(10,0), 
	"PASSENGER_ACCIDENT_PREMIUM" NUMBER(20,0), 
	"PASSENGER_ACCIDENT_SI" NUMBER(20,0), 
	"POLICY_NUMBER" VARCHAR2(255 BYTE), 
	"PREMIUM" NUMBER(20,0), 
	"PURPOSE_OF_USAGE_ID" VARCHAR2(255 BYTE), 
	"PHYSICAL_DAMAGE_PREMIUM" NUMBER(20,0), 
	"PHYSICAL_DAMAGE_SI" NUMBER(20,0), 
	"RECEIVER_NAME" VARCHAR2(255 BYTE), 
	"RECEIVER_ADDRESS" VARCHAR2(255 BYTE), 
	"RECEIVER_EMAIL" VARCHAR2(255 BYTE), 
	"RECEIVER_MOBILE" VARCHAR2(255 BYTE), 
	"RECEIVER_ADDRESS_DISTRICT" VARCHAR2(255 BYTE), 
	"REGISTRATION_NUMBER" VARCHAR2(255 BYTE), 
	"TNDS_SOCHO" VARCHAR2(255 BYTE), 
	"TNDSBB_CHECK" NUMBER(1,0), 
	"TNDSTN_CHECK" NUMBER(1,0), 
	"TNDSTN_PHI" NUMBER(20,0), 
	"TNDSTN_SOTIEN" NUMBER(20,0), 
	"TOTAL_PREMIUM" NUMBER(20,0), 
	"THIRD_PARTY_PREMIUM" NUMBER(20,0), 
	"THOI_HAN_DEN" VARCHAR2(255 BYTE), 
	"THOI_HAN_TU" VARCHAR2(255 BYTE), 
	"VCX_CHECK" NUMBER(1,0), 
	"YEAR_OF_MAKE" VARCHAR2(255 BYTE), 
	"USER_AGENT" VARCHAR2(255 BYTE), 
	"CONTACT_CODE" VARCHAR2(255 BYTE), 
	"RECEIVE_METHOD" VARCHAR2(255 BYTE), 
	"GYCBH_NUMBER" VARCHAR2(255 BYTE), 
	"OLD_GYCBH_NUMBER" VARCHAR2(255 BYTE), 
	"CONTACT_NAME" VARCHAR2(255 BYTE), 
	"CONTACT_EMAIL" VARCHAR2(255 BYTE), 
	"CONTACT_ADDRESS" VARCHAR2(255 BYTE), 
	"CONTACT_PHONENUMBER" VARCHAR2(60 BYTE), 
	 CHECK ("ID" IS NOT NULL) ENABLE, 
	 CHECK ("REQUEST_ID" IS NOT NULL) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP"  ENABLE, 
	 CONSTRAINT "UC_TMP_MOMO_CAR_REQUEST_ID" UNIQUE ("REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP" ;

CREATE SEQUENCE  "TRADEOL"."CARS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2850 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;