
  CREATE TABLE "TRADEOL"."AGENT_DOCUMENT" 
   (	"ID" NVARCHAR2(60) NOT NULL ENABLE, 
	"CODE" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	"CONTENT" BLOB NOT NULL ENABLE, 
	"TYPE" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"NOTE" VARCHAR2(255 BYTE), 
	"NUMBER_DOWNLOAD" NUMBER(20,0), 
	"USERNAME_UPLOAD" NVARCHAR2(60), 
	"DATE_UPLOAD" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(128 BYTE), 
	 CHECK ("ID" IS NOT NULL) ENABLE, 
	 CHECK ("CONTENT" IS NOT NULL) ENABLE, 
	 CHECK ("TYPE" IS NOT NULL) ENABLE, 
	 CHECK ("NAME" IS NOT NULL) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "SM_SYSTEMSMARTAPP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  
  
  CREATE SEQUENCE  "TRADEOL"."AGENT_DOCUMENT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2809 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
