  CREATE TABLE "TRADEOL"."AGENT_REMINDER" 
   (	"ID" NVARCHAR2(60) NOT NULL ENABLE, 
	"CONTACT_ID" NVARCHAR2(60), 
	"TYPE" NVARCHAR2(60), 
	"PRODUCT_CODE" NVARCHAR2(60), 
	"CONTENT" NVARCHAR2(255), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"REMINDE_DATE" DATE, 
	"NOTE" NVARCHAR2(255), 
	"ACTIVE" VARCHAR2(2 BYTE) DEFAULT 1, 
	 CONSTRAINT "ID_AGENT_REMINDER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_SYSTEMSMARTAPP"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SM_AGREEMENT" ;

   COMMENT ON COLUMN "TRADEOL"."AGENT_REMINDER"."TYPE" IS 'Mã khác hàng';
   COMMENT ON COLUMN "TRADEOL"."AGENT_REMINDER"."PRODUCT_CODE" IS 'Mục nhắc nhở. VD: CAR, BVP';
   COMMENT ON COLUMN "TRADEOL"."AGENT_REMINDER"."CONTENT" IS 'Nội dung nhắc nhở';
   COMMENT ON COLUMN "TRADEOL"."AGENT_REMINDER"."CREATED_DATE" IS 'Ngày tạo';
   COMMENT ON COLUMN "TRADEOL"."AGENT_REMINDER"."REMINDE_DATE" IS 'Ngày nhắc nhở';
   COMMENT ON COLUMN "TRADEOL"."AGENT_REMINDER"."NOTE" IS 'Ghi chú';
   COMMENT ON COLUMN "TRADEOL"."AGENT_REMINDER"."ACTIVE" IS '1: có, 0: không';



CREATE SEQUENCE  "TRADEOL"."AGENT_REMINDER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2809 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;