ALTER TABLE AGREEMENT ADD DISCOUNT VARCHAR2(20 BYTE);
ALTER TABLE AGREEMENT ADD CREATE_TYPE NUMBER default 0;
COMMENT ON COLUMN "TRADEOL"."AGREEMENT"."CREATE_TYPE" IS '0: ONL, 1: OFF, 2: Anchi';
COMMENT ON COLUMN "TRADEOL"."AGREEMENT"."DISCOUNT" IS 'Luu phan tram giam gia';