ALTER TABLE "TRADEOL".ANCHI ADD ACHI_MA_ANCHI NVARCHAR2(60);
ALTER TABLE "TRADEOL".ANCHI ADD ACHI_TEN_ANCHI NVARCHAR2(255);
ALTER TABLE "TRADEOL".ANCHI ADD ACHI_DONVI NVARCHAR2(60);
ALTER TABLE "TRADEOL".ANCHI ADD LINE_ID VARCHAR2(3);
ALTER TABLE "TRADEOL".ANCHI ADD CONTACT_ID NVARCHAR2(60);