
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BVAC_AGENCYSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BVACAGENCYSoap {


    /**
     * L\u1ea5y danh sách lo\u1ea1i \u1ea5n ch\u1ec9 theo mã \u0111\u1ea1i lý
     * 
     * @param maDaiLy
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDMLoaiAnChi", action = "http://tempuri.org/GetDMLoaiAnChi")
    @WebResult(name = "GetDMLoaiAnChiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDMLoaiAnChi", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDMLoaiAnChi")
    @ResponseWrapper(localName = "GetDMLoaiAnChiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDMLoaiAnChiResponse")
    public String getDMLoaiAnChi(
        @WebParam(name = "maDaiLy", targetNamespace = "http://tempuri.org/")
        String maDaiLy);

    /**
     * L\u1ea5y danh sách \u1ea5n ch\u1ec9 theo mã \u0111\u1ea1i lý
     * 
     * @param maDaiLy
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAnChiByAgency", action = "http://tempuri.org/GetAnChiByAgency")
    @WebResult(name = "GetAnChiByAgencyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAnChiByAgency", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAnChiByAgency")
    @ResponseWrapper(localName = "GetAnChiByAgencyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAnChiByAgencyResponse")
    public String getAnChiByAgency(
        @WebParam(name = "maDaiLy", targetNamespace = "http://tempuri.org/")
        String maDaiLy);

    /**
     * C\u1eadp nh\u1eadt danh sách \u1ea5n ch\u1ec9 \u0111ã s\u1eed d\u1ee5ng
     * 
     * @param anChis
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateListAnChi", action = "http://tempuri.org/UpdateListAnChi")
    @WebResult(name = "UpdateListAnChiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateListAnChi", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateListAnChi")
    @ResponseWrapper(localName = "UpdateListAnChiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateListAnChiResponse")
    public String updateListAnChi(
        @WebParam(name = "anChis", targetNamespace = "http://tempuri.org/")
        String anChis);

}
