
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReceiveMT", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://smsctest.baoviet.com.vn/InputMT/WebServices/ReceiveMT.asmx?wsdl")
public class ReceiveMT
    extends Service
{

    private final static URL RECEIVEMT_WSDL_LOCATION;
    private final static WebServiceException RECEIVEMT_EXCEPTION;
    private final static QName RECEIVEMT_QNAME = new QName("http://tempuri.org/", "ReceiveMT");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://smsctest.baoviet.com.vn/InputMT/WebServices/ReceiveMT.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECEIVEMT_WSDL_LOCATION = url;
        RECEIVEMT_EXCEPTION = e;
    }

    public ReceiveMT() {
        super(__getWsdlLocation(), RECEIVEMT_QNAME);
    }

    public ReceiveMT(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECEIVEMT_QNAME, features);
    }

    public ReceiveMT(URL wsdlLocation) {
        super(wsdlLocation, RECEIVEMT_QNAME);
    }

    public ReceiveMT(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECEIVEMT_QNAME, features);
    }

    public ReceiveMT(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceiveMT(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReceiveMTSoap
     */
    @WebEndpoint(name = "ReceiveMTSoap")
    public ReceiveMTSoap getReceiveMTSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ReceiveMTSoap"), ReceiveMTSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveMTSoap
     */
    @WebEndpoint(name = "ReceiveMTSoap")
    public ReceiveMTSoap getReceiveMTSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ReceiveMTSoap"), ReceiveMTSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECEIVEMT_EXCEPTION!= null) {
            throw RECEIVEMT_EXCEPTION;
        }
        return RECEIVEMT_WSDL_LOCATION;
    }

}
