
package doc.glite;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DocGLitev2018Service", targetNamespace = "http://lite.ws.bv.com/", wsdlLocation = "http://10.29.85.24:7006/DocGLite/DocGLitev2018?wsdl")
public class DocGLitev2018Service
    extends Service
{

    private final static URL DOCGLITEV2018SERVICE_WSDL_LOCATION;
    private final static WebServiceException DOCGLITEV2018SERVICE_EXCEPTION;
    private final static QName DOCGLITEV2018SERVICE_QNAME = new QName("http://lite.ws.bv.com/", "DocGLitev2018Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.29.85.24:7006/DocGLite/DocGLitev2018?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCGLITEV2018SERVICE_WSDL_LOCATION = url;
        DOCGLITEV2018SERVICE_EXCEPTION = e;
    }

    public DocGLitev2018Service() {
        super(__getWsdlLocation(), DOCGLITEV2018SERVICE_QNAME);
    }

    public DocGLitev2018Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCGLITEV2018SERVICE_QNAME, features);
    }

    public DocGLitev2018Service(URL wsdlLocation) {
        super(wsdlLocation, DOCGLITEV2018SERVICE_QNAME);
    }

    public DocGLitev2018Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCGLITEV2018SERVICE_QNAME, features);
    }

    public DocGLitev2018Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocGLitev2018Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocGLitev2018
     */
    @WebEndpoint(name = "DocGLitev2018Port")
    public DocGLitev2018 getDocGLitev2018Port() {
        return super.getPort(new QName("http://lite.ws.bv.com/", "DocGLitev2018Port"), DocGLitev2018.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocGLitev2018
     */
    @WebEndpoint(name = "DocGLitev2018Port")
    public DocGLitev2018 getDocGLitev2018Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://lite.ws.bv.com/", "DocGLitev2018Port"), DocGLitev2018.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCGLITEV2018SERVICE_EXCEPTION!= null) {
            throw DOCGLITEV2018SERVICE_EXCEPTION;
        }
        return DOCGLITEV2018SERVICE_WSDL_LOCATION;
    }

}
