
package vn.bluezone.w2m;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SMSSoap", targetNamespace = "http://w2m.bluezone.vn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SMSSoap {


    /**
     * 
     * @param password
     * @param phone
     * @param requestId
     * @param sms
     * @param serviceid
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendMT", action = "http://w2m.bluezone.vn/SendMT")
    @WebResult(name = "SendMTResult", targetNamespace = "http://w2m.bluezone.vn/")
    @RequestWrapper(localName = "SendMT", targetNamespace = "http://w2m.bluezone.vn/", className = "vn.bluezone.w2m.SendMT")
    @ResponseWrapper(localName = "SendMTResponse", targetNamespace = "http://w2m.bluezone.vn/", className = "vn.bluezone.w2m.SendMTResponse")
    public String sendMT(
        @WebParam(name = "phone", targetNamespace = "http://w2m.bluezone.vn/")
        String phone,
        @WebParam(name = "sms", targetNamespace = "http://w2m.bluezone.vn/")
        String sms,
        @WebParam(name = "serviceid", targetNamespace = "http://w2m.bluezone.vn/")
        String serviceid,
        @WebParam(name = "request_id", targetNamespace = "http://w2m.bluezone.vn/")
        String requestId,
        @WebParam(name = "username", targetNamespace = "http://w2m.bluezone.vn/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://w2m.bluezone.vn/")
        String password);

}
